version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api                    # ← относительный
    container_name: analyzer_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - llm_analyzer_network

networks:
  llm_analyzer_network:
    external: true